
ignored = ["google.golang.org/appengine*"]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "code.gitea.io/git"

[[constraint]]
  branch = "master"
  name = "code.gitea.io/sdk"

[[constraint]]
#  branch = "master"
  revision = "c74e08f039e56cef576e4336382b2a2d12d9e026"
  name = "github.com/blevesearch/bleve"
#Not targetting v0.7.0 since standard where use only just after this tag

[[constraint]]
  revision = "12dd70caea0268ac0d6c2707d0611ef601e7c64e"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  revision = "2bf8f2a19ec09c670e931282edfe6567f6be21c9"
  name = "golang.org/x/text"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[override]]
  name = "github.com/go-xorm/xorm"
  revision = "401f4ee8ff8cbc40a4754cb12192fbe4f02f3979"

[[override]]
  name = "github.com/go-xorm/builder"
  version = "0.3.3"

[[override]]
  name = "github.com/go-sql-driver/mysql"
  revision = "d523deb1b23d913de5bdada721a6071e71283618"

[[override]]
  name = "github.com/mattn/go-sqlite3"
  revision = "c7c4067b79cc51e6dfdcef5c702e74b1e0fa7c75"

[[override]]
  name = "github.com/gorilla/mux"
  revision = "757bef944d0f21880861c2dd9c871ca543023cba"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.1"

[[constraint]]
  name = "github.com/lafriks/xormstore"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lunny/dingtalk_webhook"

[[constraint]]
  name = "github.com/markbates/goth"
  version = "1.47.2"

[[constraint]]
  branch = "master"
  name = "github.com/mcuadros/go-version"

[[constraint]]
  branch = "master"
  name = "github.com/russross/blackfriday"

[[constraint]]
  branch = "master"
  name = "github.com/tstranex/u2f"

[[constraint]]
  name = "gopkg.in/editorconfig/editorconfig-core-go.v1"
  version = "1.2.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/gomail.v2"

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "1.31.1"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.4.1"

[[constraint]]
  name = "gopkg.in/macaron.v1"
  version = "1.2.4"

[[constraint]]
  name = "gopkg.in/testfixtures.v2"
  version = "2.0.0"

[[override]]
  name = "github.com/boltdb/bolt"
  revision = "ccd680d8c1a0179ac3d68f692b01e1a1589cbfc7"
  source = "github.com/go-gitea/bolt"

[[override]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"
