name: Gitea tests

on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'  # Java version you want
          java-package: jdk
          architecture: x64
          distribution: 'temurin'  # Specify the JDK distribution (e.g., temurin, adoptopenjdk, zulu, amazon-corretto)

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        run: mvn clean test

  TriggerDeployment:
    runs-on: ubuntu-latest
    needs: Build  # Trigger after Build job completes
    env:
      SPOTIFY_TESTING_REPO_NAME: giteaProject  # Your testing repo name
      UI_TESTING_WORKFLOW_ID: ui-testing  # Workflow ID from SpotifyTesting
    steps:
      - name: Trigger the Selenium testing workflow
        run: |
          curl -X POST \
           -H "Authorization: Bearer ${{ secrets.GITHUB_ACCESS_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           -d "{\"ref\": \"main\", \"inputs\": {\"browser\": \"chrome\"}}" \
           https://api.github.com/repos/$SPOTIFY_TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches
