blank_issues_enabled: false
contact_links:
  - name: Discuss Forkana
    url: https://github.com/okTurtles/forkana/discussions
    about: Use issues to report bugs or request features. Everything else goes here.
