baseurl: https://docs.gitea.io/
languageCode: en-us
title: Docs
theme: gitea

defaultContentLanguage: en-us
defaultContentLanguageInSubdir: true
enableMissingTranslationPlaceholders: true
enableEmoji: true

permalinks:
  post: /:year/:month/:title/
  doc: /:slug/
  page: /:slug/
  default: /:slug/

params:
  description: Git with a cup of tea
  author: The Gitea Authors
  website: https://docs.gitea.io
  version: 1.11.2

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  page:
    - name: Website
      url: https://gitea.io/en-us/
      weight: 10
      pre: home
    - name: Docs
      url: /en-us/
      weight: 20
      pre: question
      post: active
    - name: API
      url: https://try.gitea.io/api/swagger
      weight: 45
      pre: plug
    - name: Blog
      url: https://blog.gitea.io/
      weight: 30
      pre: rss
    - name: Code
      url: https://code.gitea.io/
      weight: 40
      pre: code
    - name: Downloads
      url: https://dl.gitea.io/
      weight: 50
      pre: download
    - name: GitHub
      url: https://github.com/go-gitea/
      weight: 60
      pre: github
    - name: Discord Chat
      url: https://discord.gg/NsatcWJ
      weight: 70
      pre: comment
    - name: Forum
      url: https://discourse.gitea.io/
      weight: 80
      pre: group

languages:
  en-us:
    weight: 0
    languageName: English

  zh-cn:
    weight: 1
    languageName: 中文(简体)
    menu:
      page:
        - name: 网站
          url: https://gitea.io/zh-cn/
          weight: 10
          pre: home
        - name: 文档
          url: /zh-cn/
          weight: 20
          pre: question
          post: active
        - name: API
          url: https://try.gitea.io/api/swagger
          weight: 45
          pre: plug
        - name: 博客
          url: https://blog.gitea.io/
          weight: 30
          pre: rss
        - name: 导入
          url: https://code.gitea.io/
          weight: 40
          pre: code
        - name: 下载
          url: https://dl.gitea.io/
          weight: 50
          pre: download
        - name: GitHub
          url: https://github.com/go-gitea/
          weight: 60
          pre: github
        - name: Discord Chat
          url: https://discord.gg/NsatcWJ
          weight: 70
          pre: comment
        - name: Forum
          url: https://discourse.gitea.io/
          weight: 80
          pre: group

  zh-tw:
    weight: 2
    languageName: 中文(繁體)
    menu:
      page:
        - name: 網站
          url: https://gitea.io/zh-tw/
          weight: 10
          pre: home
        - name: 文件
          url: /zh-tw/
          weight: 20
          pre: question
          post: active
        - name: API
          url: https://try.gitea.io/api/swagger
          weight: 45
          pre: plug
        - name: 部落格
          url: https://blog.gitea.io/
          weight: 30
          pre: rss
        - name: 程式碼
          url: https://code.gitea.io/
          weight: 40
          pre: code
        - name: 下载
          url: https://dl.gitea.io/
          weight: 50
          pre: download
        - name: GitHub
          url: https://github.com/go-gitea/
          weight: 60
          pre: github
        - name: Discord Chat
          url: https://discord.gg/NsatcWJ
          weight: 70
          pre: comment
        - name: Forum
          url: https://discourse.gitea.io/
          weight: 80
          pre: group

  pt-br:
    weight: 3
    languageName: Português Brasileiro
    menu:
      page:
        - name: Página inicial
          url: https://gitea.io/pt-br/
          weight: 10
          pre: home
        - name: Documentação
          url: /pt-br/
          weight: 20
          pre: question
          post: active
        - name: API
          url: https://try.gitea.io/api/swagger
          weight: 45
          pre: plug
        - name: Blog
          url: https://blog.gitea.io/
          weight: 30
          pre: rss
        - name: Código-fonte
          url: https://code.gitea.io/
          weight: 40
          pre: code
        - name: Downloads
          url: https://dl.gitea.io/
          weight: 50
          pre: download
        - name: GitHub
          url: https://github.com/go-gitea/
          weight: 60
          pre: github
        - name: Chat no Discord
          url: https://discord.gg/NsatcWJ
          weight: 70
          pre: comment
        - name: Forum
          url: https://discourse.gitea.io/
          weight: 80
          pre: group

  nl-nl:
    weight: 4
    languageName: Nederlands
    menu:
      page:
        - name: Website
          url: https://gitea.io/nl-nl/
          weight: 10
          pre: home
        - name: Docs
          url: /nl-nl/
          weight: 20
          pre: question
          post: active
        - name: API
          url: https://try.gitea.io/api/swagger
          weight: 45
          pre: plug
        - name: Blog
          url: https://blog.gitea.io/
          weight: 30
          pre: rss
        - name: Code
          url: https://code.gitea.io/
          weight: 40
          pre: code
        - name: Downloads
          url: https://dl.gitea.io/
          weight: 50
          pre: download
        - name: GitHub
          url: https://github.com/go-gitea/
          weight: 60
          pre: github
        - name: Discord Chat
          url: https://discord.gg/NsatcWJ
          weight: 70
          pre: comment
        - name: Forum
          url: https://discourse.gitea.io/
          weight: 80
          pre: group

  fr-fr:
    weight: 5
    languageName: Français
    menu:
      page:
        - name: Site
          url: https://gitea.io/en-us/
          weight: 10
          pre: home
          post: active
        - name: Documentation
          url: /fr-fr/
          weight: 20
          pre: question
        - name: API
          url: https://try.gitea.io/api/swagger
          weight: 45
          pre: plug
        - name: Blog
          url: https://blog.gitea.io/
          weight: 30
          pre: rss
        - name: Code
          url: https://code.gitea.io/
          weight: 40
          pre: code
        - name: Téléchargement
          url: https://dl.gitea.io/
          weight: 50
          pre: download
        - name: GitHub
          url: https://github.com/go-gitea/
          weight: 60
          pre: github
        - name: Discord Chat
          url: https://discord.gg/NsatcWJ
          weight: 70
          pre: comment
        - name: Forum
          url: https://discourse.gitea.io/
          weight: 80
          pre: group
