# name: Load Testing with JMeter

# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: read
#   actions: read
#   checks: write

# jobs:
#   jmeter:
#     name: Run JMeter Tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Run JMeter Action on a test
#         uses: rbhadti94/apache-jmeter-action@v0.5.0
#         with:
#           testFilePath: tests/jmeter/gite-test-plan.jmx
#           outputReportsFolder: reports/
#           args: "--loglevel INFO"

#       - name: Upload JMeter Test Results
#         uses: actions/upload-artifact@v4
#         with:
#           name: jmeter-test-results
#           path: reports/